# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"

# 数据库配置
database:
  type: "sqlite3"  # 使用 SQLite 作为开发环境数据库
  path: "./data/webterminal.db"

# 会话配置
session:
  timeout: 3600  # 会话超时时间（秒）
  cleanup_interval: 300  # 清理间隔（秒）

# 安全配置
security:
  jwt_secret: "your-secret-key"  # JWT 密钥
  token_expiry: 86400  # Token 过期时间（秒）

# SSH配置
ssh:
  timeout: 30  # SSH 连接超时时间（秒）
  keepalive: 60  # SSH 保活间隔（秒）
  buffer_size: 8192  # 缓冲区大小（字节）

# 日志配置
log:
  level: "debug"  # 日志级别
  file: "./logs/webterminal.log"  # 日志文件路径
  max_size: 100  # 单个日志文件最大大小（MB）
  max_backups: 3  # 最大保留日志文件数
  max_age: 28  # 日志文件最大保留天数
  compress: true  # 是否压缩旧日志文件 